name: Dependabot Auto-Merge
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check if PR is for minor/patch updates only
        id: check-update-type
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const isMajorUpdate = title.includes('(major)') || title.match(/:\s*\d+\.\d+\.\d+\s*→\s*\d+\.\d+\.\d+/) && 
              title.match(/:\s*(\d+)\.\d+\.\d+\s*→\s*(\d+)\.\d+\.\d+/) &&
              title.match(/:\s*(\d+)\.\d+\.\d+\s*→\s*(\d+)\.\d+\.\d+/)[1] !== title.match(/:\s*(\d+)\.\d+\.\d+\s*→\s*(\d+)\.\d+\.\d+/)[2];
            
            if (isMajorUpdate) {
              console.log('Major update detected, skipping auto-merge');
              return { shouldMerge: false };
            }
            
            return { shouldMerge: true };
      
      - name: Enable auto-merge for Dependabot PRs
        if: steps.check-update-type.outputs.result != 'false'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
