# Fromn Qwen

name: Dependabot Auto-Merge
on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              auto_merge: {
                enabled: true,
                merge_method: 'squash'
              }
            })
